name: flame_dodge_ball
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

workspace:
  - packages/application
  - packages/domain
  - packages/ui
  - packages/data
  - packages/assets

dependencies:
  application:
    path: packages/application
  data:
    path: packages/data
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  ui:
    path: packages/ui

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_lints: ^6.0.0
  hooksman: 3.1.2
  spider: ^4.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/animations/boss/
    - assets/animations/enemy/
    - assets/animations/platform/
    - assets/animations/players/
    - assets/audio/
    - assets/images/boss/
    - assets/images/dodge_balls/
    - assets/images/enemies/
    - assets/images/platform/
    - assets/images/players/
    - assets/sprites/boss/
    - assets/sprites/dodge_balls/
    - assets/sprites/platform/
    - assets/sprites/players/

dependency_overrides:
  analyzer: ^9.0.0

scripts: derry.yaml
