name: flame_dodge_ball
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.34.0
  equatable_annotations: ^1.3.0
  bloc: ^9.2.0
  copy_with_extension: ^11.0.0
  equatable: ^2.0.7
  flame_behaviors: ^1.3.1
  flame_bloc: ^1.12.19
  flame_splash_screen: ^0.3.1+2
  flame_tiled: ^3.0.9
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_lints: ^6.0.0
  equatable_gen: ^1.3.0
  build_runner: ^2.10.4
  copy_with_extension_gen: ^11.0.0
  flame_lint: ^1.4.2
  very_good_analysis: ^10.0.0
  bloc_lint: ^0.3.6

flutter:
  uses-material-design: true
