name: flame_dodge_ball
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

workspace:
  - packages/application
  - packages/domain
  - packages/ui

dependencies:
  flutter:
    sdk: flutter
  application:
    path: packages/application
  domain:
    path: packages/domain
  ui:
    path: packages/ui
  get_it: ^9.2.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flame_lint: ^1.4.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  analyzer: ^8.2.0
