name: flame_dodge_ball
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

workspace:
  - packages/application
  - packages/domain
  - packages/ui
  - packages/data
  - packages/assets

dependencies:
  application:
    path: packages/application
  data:
    path: packages/data
  domain:
    path: packages/domain
  flutter:
    sdk: flutter
  get_it: ^9.2.0
  ui:
    path: packages/ui

dev_dependencies:
  flame_lint: ^1.4.2
  flutter_lints: ^6.0.0
  hooksman: 3.1.2
  spider: ^4.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/audio
    - assets/images/boss/animations
    - assets/images/boss/images
    - assets/images/boss/sprites
    - assets/images/dodge_balls/images
    - assets/images/dodge_balls/sprites
    - assets/images/enemies/sprites
    - assets/images/platform
    - assets/images/platform/assets/ui
    - assets/images/players
    - assets/images/players/player
    - assets/images/players/player/json

dependency_overrides:
  analyzer: ^9.0.0

scripts: derry.yaml
