name: application
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  bloc: ^9.2.0
  change_case: ^2.2.0
  domain:
    path: ../domain
  equatable: ^2.0.7
  get_it: ^9.2.0
  get_it_injector: ^0.6.0

dev_dependencies:
  bloc_enhancer_gen: ^0.6.0
  build_runner: ^2.10.4
  equatable_gen: ^1.3.0
  get_it_injector_gen: ^0.6.0
