name: ui
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  application:
    path: ../application
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flame: ^1.34.0
  flame_behaviors: ^1.3.1
  flame_bloc: ^1.12.19
  flame_splash_screen: ^0.3.1+2
  flame_tiled: ^3.0.9
  flex_color_scheme: ^8.4.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
