name: domain
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.10.4
  equatable_gen: ^1.3.0
